#version 450
layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout (set = 0, binding = 0) uniform sampler2D uSrc;
layout (set = 0, binding = 1, r32f) writeonly uniform image2D uDst;

void main() {
    ivec2 dstSize = imageSize(uDst);
    ivec2 p = ivec2(gl_GlobalInvocationID.xy);
    if (p.x >= dstSize.x || p.y >= dstSize.y) return;

    float d = texelFetch(uSrc, p, 0).r;
    imageStore(uDst, p, vec4(d, 0.0, 0.0, 0.0));
}
